// keygen generates RSA-2048 key pair and AES-256 encryption key,
// then writes a ready-to-use .env to stdout.
//
// Usage:
//
//	go run ./cmd/keygen > .env
//	make gen-env
package main

import (
	"crypto/rand"
	"crypto/rsa"
	"crypto/x509"
	"encoding/base64"
	"encoding/hex"
	"encoding/pem"
	"fmt"
	"io"
	"os"
)

func main() {
	// RSA-2048 key pair
	privateKey, err := rsa.GenerateKey(rand.Reader, 2048)
	if err != nil {
		fmt.Fprintf(os.Stderr, "error generating RSA key: %v\n", err)
		os.Exit(1)
	}

	// Private key → PKCS8 PEM → Base64
	privBytes, err := x509.MarshalPKCS8PrivateKey(privateKey)
	if err != nil {
		fmt.Fprintf(os.Stderr, "error marshaling private key: %v\n", err)
		os.Exit(1)
	}
	privPEM := pem.EncodeToMemory(&pem.Block{Type: "PRIVATE KEY", Bytes: privBytes})

	// Public key → PKIX PEM → Base64
	pubBytes, err := x509.MarshalPKIXPublicKey(&privateKey.PublicKey)
	if err != nil {
		fmt.Fprintf(os.Stderr, "error marshaling public key: %v\n", err)
		os.Exit(1)
	}
	pubPEM := pem.EncodeToMemory(&pem.Block{Type: "PUBLIC KEY", Bytes: pubBytes})

	// AES-256 key → 32 random bytes → 64-char hex
	encKeyBytes := make([]byte, 32)
	if _, err := io.ReadFull(rand.Reader, encKeyBytes); err != nil {
		fmt.Fprintf(os.Stderr, "error generating encryption key: %v\n", err)
		os.Exit(1)
	}

	fmt.Print(`# TeamClaw Go API — development environment
# Generated by 'make gen-env' — DO NOT COMMIT

# ── PostgreSQL ───────────────────────────────────────────
POSTGRES_USER=teamclaw
POSTGRES_PASSWORD=devpass
POSTGRES_DB=teamclaw

# ── Redis ────────────────────────────────────────────────
# (Used by the server; set automatically in docker-compose)
REDIS_URL=redis://localhost:6379

# ── JWT RS256 ────────────────────────────────────────────
`)
	fmt.Printf("JWT_PRIVATE_KEY=%s\n", base64.StdEncoding.EncodeToString(privPEM))
	fmt.Printf("JWT_PUBLIC_KEY=%s\n", base64.StdEncoding.EncodeToString(pubPEM))
	fmt.Print(`
# ── AES-256 Encryption ───────────────────────────────────
`)
	fmt.Printf("ENCRYPTION_KEY=%s\n", hex.EncodeToString(encKeyBytes))
	fmt.Print(`
# ── Server ───────────────────────────────────────────────
PORT=3200
GIN_MODE=debug
`)
}
